/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package algos.project;

import java.util.Date;
import java.util.Properties;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.mail.Message;
import javax.mail.MessagingException;
import javax.mail.PasswordAuthentication;
import javax.mail.Session;
import javax.mail.Transport;
import javax.mail.internet.InternetAddress;
import javax.mail.internet.MimeMessage;
import javax.swing.JTextArea;

/**
 *
 * @author hp
 */
public class Design extends javax.swing.JFrame {

    /**
     * Creates new form Design
     */
    public Design() {
        initComponents();
    }

    public void sendMail(String[] To,String[] Cc,String[] Bcc,String sub, String message){
        String host,user,pass,from,subject,messageText;
        host ="smtp.gmail.com" ;
        user = "shashdude2108@gmail.com";
        pass = "mygoal@IITB";
        from = user;
        subject = sub;
        messageText = message; 
        try{
        
            if(To==null){
                System.out.println("dead");
            }
            System.out.println("Running");
            boolean sessionDebug = false;

            Properties props = System.getProperties();

            props.put("mail.smtp.starttls.enable", true);
            props.put("mail.smtp.host", host);
            props.put("mail.smtp.port", "587");
            props.put("mail.smtp.auth", true);

            java.security.Security.addProvider(new com.sun.net.ssl.internal.ssl.Provider());
            Session mailSession = Session.getDefaultInstance(props, null);
            
            mailSession.setDebug(sessionDebug);
            Message msg = new MimeMessage(mailSession);
            msg.setFrom(new InternetAddress(from));
            InternetAddress[] address_to=new InternetAddress[getLengthNotNull(To)];
            for(int i=0;To[i]!=null;i++){
                InternetAddress ia=new InternetAddress(To[i]);
                address_to[i]=ia; 
            }
            InternetAddress[] address_cc=new InternetAddress[getLengthNotNull(Cc)];
            for(int i=0;Cc[i]!=null;i++){
                InternetAddress ia=new InternetAddress(To[i]);
                address_cc[i]=ia;
            }
            InternetAddress[] address_bcc=new InternetAddress[getLengthNotNull(Bcc)];
            for(int i=0;Bcc[i]!=null;i++){
                InternetAddress ia=new InternetAddress(To[i]);
                address_bcc[i]=ia;
            }
            msg.setRecipients(Message.RecipientType.TO, address_to);
            msg.setRecipients(Message.RecipientType.CC, address_cc);
            msg.setRecipients(Message.RecipientType.BCC, address_bcc);
            msg.setSubject(subject); 
            msg.setSentDate(new Date());
            msg.setText(messageText);

           Transport transport=mailSession.getTransport("smtp");
           transport.connect(host, user, pass);
           transport.sendMessage(msg, msg.getAllRecipients());
           transport.close();
           System.out.println("Message sent successfully");
        }catch(Exception ex){
                System.out.println(ex);
            }
        
    }
    public String[] getAddresses(String text){
        String address[]=new String[50];
        int k=0;
        String s="";
        for(int i=0;i<text.length();i++){
            s=s+text.charAt(i);
            if(i>=3){
                if(text.toLowerCase().charAt(i-3)=='.' &&
                    text.toLowerCase().charAt(i-2)=='c' &&
                    text.toLowerCase().charAt(i-1)=='o' &&
                    text.toLowerCase().charAt(i)=='m'
                        ){
                        address[k]=s;
                        k++;
                        s="";
                        i=i+1;
                }
            }
        }
        return address;
    }
    public int getLengthNotNull(String array[]){
        int count=0;
        while(array[count]!=null){
            count++;
        }
        return count;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        msgTa = new javax.swing.JTextArea();
        toTf = new javax.swing.JTextField();
        subTf = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        ccTa = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        bccTa = new javax.swing.JTextArea();
        SendBtn = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(720, 540));
        setMinimumSize(new java.awt.Dimension(720, 540));
        setPreferredSize(new java.awt.Dimension(720, 540));
        setSize(new java.awt.Dimension(720, 540));
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Courier New", 1, 24)); // NOI18N
        jLabel1.setText("Subject:");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(36, 175, 112, 28);

        jLabel2.setFont(new java.awt.Font("Courier New", 1, 24)); // NOI18N
        jLabel2.setText("To:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(36, 64, 42, 28);

        jLabel3.setFont(new java.awt.Font("Courier New", 1, 24)); // NOI18N
        jLabel3.setText("Bcc:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(36, 137, 56, 28);

        jLabel4.setFont(new java.awt.Font("Courier New", 1, 24)); // NOI18N
        jLabel4.setText("Cc:");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(36, 103, 42, 28);

        msgTa.setColumns(20);
        msgTa.setRows(5);
        jScrollPane1.setViewportView(msgTa);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(36, 221, 647, 215);

        toTf.setFont(new java.awt.Font("Monospaced", 0, 13)); // NOI18N
        toTf.setMaximumSize(new java.awt.Dimension(517, 28));
        toTf.setMinimumSize(new java.awt.Dimension(517, 28));
        toTf.setPreferredSize(new java.awt.Dimension(517, 28));
        toTf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                toTfActionPerformed(evt);
            }
        });
        getContentPane().add(toTf);
        toTf.setBounds(166, 65, 517, 28);

        subTf.setFont(new java.awt.Font("Monospaced", 0, 13)); // NOI18N
        subTf.setMaximumSize(new java.awt.Dimension(517, 28));
        subTf.setMinimumSize(new java.awt.Dimension(517, 28));
        subTf.setPreferredSize(new java.awt.Dimension(517, 28));
        subTf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subTfActionPerformed(evt);
            }
        });
        getContentPane().add(subTf);
        subTf.setBounds(166, 175, 517, 28);

        jLabel5.setFont(new java.awt.Font("Courier New", 1, 36)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Compose E-Mail");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(0, 10, 720, 39);

        jScrollPane2.setPreferredSize(new java.awt.Dimension(166, 113));

        ccTa.setColumns(20);
        ccTa.setRows(5);
        ccTa.setMaximumSize(new java.awt.Dimension(517, 28));
        ccTa.setMinimumSize(new java.awt.Dimension(517, 28));
        ccTa.setPreferredSize(new java.awt.Dimension(498, 28));
        jScrollPane2.setViewportView(ccTa);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(166, 103, 517, 28);

        bccTa.setColumns(20);
        bccTa.setRows(5);
        bccTa.setMaximumSize(new java.awt.Dimension(517, 28));
        bccTa.setMinimumSize(new java.awt.Dimension(517, 28));
        bccTa.setPreferredSize(new java.awt.Dimension(498, 28));
        jScrollPane3.setViewportView(bccTa);

        getContentPane().add(jScrollPane3);
        jScrollPane3.setBounds(166, 137, 517, 28);

        SendBtn.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 18)); // NOI18N
        SendBtn.setText("SEND");
        SendBtn.setAlignmentY(0.0F);
        SendBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        SendBtn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        SendBtn.setMaximumSize(new java.awt.Dimension(100, 30));
        SendBtn.setMinimumSize(new java.awt.Dimension(100, 30));
        SendBtn.setPreferredSize(new java.awt.Dimension(100, 30));
        SendBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SendBtnActionPerformed(evt);
            }
        });
        getContentPane().add(SendBtn);
        SendBtn.setBounds(310, 454, 100, 30);

        jLabel6.setBackground(new java.awt.Color(255, 255, 153));
        jLabel6.setMaximumSize(new java.awt.Dimension(720, 500));
        jLabel6.setMinimumSize(new java.awt.Dimension(720, 500));
        jLabel6.setOpaque(true);
        jLabel6.setPreferredSize(new java.awt.Dimension(720, 500));
        getContentPane().add(jLabel6);
        jLabel6.setBounds(0, 0, 720, 500);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void toTfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_toTfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_toTfActionPerformed

    private void subTfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subTfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_subTfActionPerformed

    private void SendBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SendBtnActionPerformed
        String[] address_to=getAddresses(toTf.getText());
        String[] address_cc=getAddresses(ccTa.getText());
        String[] address_bcc=getAddresses(bccTa.getText());
        System.out.println(getLengthNotNull(address_cc));

            sendMail(address_to,address_cc,address_bcc,subTf.getText(),msgTa.getText());
            toTf.setText("");
            subTf.setText("");
            msgTa.setText("");
            ccTa.setText("");
            bccTa.setText("");
        
    }//GEN-LAST:event_SendBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Design.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Design.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Design.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Design.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Design().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton SendBtn;
    private javax.swing.JTextArea bccTa;
    private javax.swing.JTextArea ccTa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextArea msgTa;
    private javax.swing.JTextField subTf;
    private javax.swing.JTextField toTf;
    // End of variables declaration//GEN-END:variables
}
